### PR TITLE
fix(remoter): 修复历史会话记录没有滚动条的bug

### LINKED ISSUE #346: 🐛 [Bug]: 会话历史太多时，无法滚动到底部查看
### Version of @opentiny/next-sdk (and @opentiny/next-remoter if applicable)

latest

### Node.js Version

latest

### Link to minimal reproduction

如下，超出的部分看不到了
Image

### Step to reproduce

如上

### What is expected

_No response_

### What is actually happening

_No response_

### What is your project name

后台管理系统

### Any additional comments (optional)

_No response_

### PR DESCRIPTION
**Pull request by shenjunjian**
# Pull Request (OpenTiny NEXT-SDKs)

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/next-sdk/blob/dev/CONTRIBUTING.md#pull-request-specification)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build-related changes
- [ ] CI-related changes
- [ ] Documentation-related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #346 

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Summary by CodeRabbit

* **Style**
  * Enhanced the chat history panel with improved scrolling functionality and refined spacing for better visual organization and usability.

### CODE REVIEW

**Review by zzcr — APPROVED** [review]

File: packages/next-remoter/src/components/TinyRobotChat.vue [hunk 1]
```diff
@@ -816,6 +816,19 @@ defineExpose({
 .tr-history-demo {
   height: 100%;
   width: 100%;
+
+  :deep(.tr-history__group) {
+    height: 100%;
+    overflow: scroll;
+  }
```
Comment (kagol) [inline packages/next-remoter/src/components/TinyRobotChat.vue:823]: @shenjunjian 这样样式重复了，建议移除一个

File: packages/next-remoter/src/components/TinyRobotChat.vue [hunk 2]
```diff
@@ -816,6 +816,19 @@ defineExpose({
...
+
+  :deep(.tr-history__group) {
+    height: 100%;
+    overflow: scroll;
```
Comment (kagol) [inline packages/next-remoter/src/components/TinyRobotChat.vue:827]: 另外设置为 `overflow: scroll;` 会导致只有少量内容也出现滚动条，并且横向、纵向都会出现空的滚动条。

Image

Comment (kagol) [inline packages/next-remoter/src/components/TinyRobotChat.vue:827]: 建议这样写：

```suggestion
    overflow-y: auto
```

File: packages/next-remoter/src/components/TinyRobotChat.vue [hunk 3]
```diff
@@ -816,6 +816,19 @@ defineExpose({
...
   height: 100%;
   width: 100%;
+
+  :deep(.tr-history__group) {
+    height: 100%;
+    overflow: scroll;
+  }
+
+  :deep(.tr-history__group) {
+    height: 100%;
```
Comment (kagol) [inline packages/next-remoter/src/components/TinyRobotChat.vue:826]: 另外 `height: 100%;` 会导致滚动条跟底部贴得太紧，并且出现一个凸起的小白块，如下图所示：

Image
